<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-array-Indexing/Slicing" data-toc-modified-id="NumPy-array-Indexing/Slicing-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy array Indexing/Slicing</a></span></li></ul></div>

In [1]:
import pandas as pd
import numpy as np

## NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).


In [1]:
from si.io.csv_file import read_csv

In [2]:
filename= r'C:\Users\Asus\Desktop\MESTRADO BI 2324\2ANO\SIB\portfólio\si\datasets\iris\iris.csv'  

In [3]:
iris_data = read_csv(filename, sep=",", features=True, label=True)

In [5]:
features=iris_data.features
print(features)
label=iris_data.label
print(label)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
class


1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [14]:
pn_var=iris_data.X[:,-2]
print("Dimension of the array:", pn_var.shape)

Dimension of the array: (150,)


In [50]:
#in case it is the penultimate of the independent variables (that is, the first 4 columns) and not the penultimate column that corresponds to the last independent variable in the array
pn_var2=iris_data.X[:,-3]
print("Dimension of the array:", pn_var2.shape)

Dimension of the array: (150,)


1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [53]:
last_ten=iris_data.X[-10:,0:4]

In [54]:
print(last_ten)

[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.0 5.2 2.3]
 [6.3 2.5 5.0 1.9]
 [6.5 3.0 5.2 2.0]
 [6.2 3.4 5.4 2.3]
 [5.9 3.0 5.1 1.8]]


In [52]:
mean_last_ten = np.mean(last_ten, axis=0)
print("Last ten samples means by feature:", mean_last_ten)  

Last ten samples means by feature: [6.450000000000001 3.0300000000000002 5.33 2.1700000000000004]


1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [55]:
iris_data_ind=iris_data.X[:,:4]

In [56]:
mask = np.all(iris_data_ind <= 6, axis=1)
filtered_samples = iris_data_ind[mask, :]
print("Samples with values less than or equal to 6 for all independent variables/features:", filtered_samples.shape[0])

Samples with values less than or equal to 6 for all independent variables/features: 89


1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain?

In [57]:
mask_dif=iris_data.X[:, -1] != 'Iris-setosa'

In [60]:
samples_dif=iris_data.X[mask_dif]
print("Number of samples with a class different from «Iris-setosa»:", samples_dif.shape[0])

Number of samples with a class different from «Iris-setosa»: 100
