In [1]:
from si.neural_networks.layers import Dropout
import numpy as np

Treinamento:
Entrada:
[[ 0.11551678 -2.18033755 -0.20558071]
 [-1.36485281 -1.53388933 -0.48920917]
 [ 0.07214588  1.04042433 -0.90363809]]
Saída com Dropout:
[[ 0.         -4.36067509 -0.        ]
 [-2.72970562 -3.06777865 -0.97841834]
 [ 0.14429176  2.08084867 -0.        ]]
Máscara aplicada:
[[0 1 0]
 [1 1 1]
 [1 1 0]]

Inferência:
Entrada:
[[ 0.11551678 -2.18033755 -0.20558071]
 [-1.36485281 -1.53388933 -0.48920917]
 [ 0.07214588  1.04042433 -0.90363809]]
Saída com Dropout (sem alteração):
[[ 0.11551678 -2.18033755 -0.20558071]
 [-1.36485281 -1.53388933 -0.48920917]
 [ 0.07214588  1.04042433 -0.90363809]]


In [2]:
probability = 0.5  # Taxa de dropout (50%)
input_data = np.random.randn(3, 3)  # Entrada aleatória (3x3)

# Criação da camada Dropout
dropout_layer = Dropout(probability=probability)

# Teste durante o treinamento
print("Treinamento:")
output_train = dropout_layer.forward_propagation(input_data, training=True)
print("Entrada:")
print(input_data)
print("Saída com Dropout:")
print(output_train)
print("Máscara aplicada:")
print(dropout_layer.mask)

# Teste durante a inferência (sem dropout)
print("\nInferência:")
output_infer = dropout_layer.forward_propagation(input_data, training=False)
print("Entrada:")
print(input_data)
print("Saída com Dropout (sem alteração):")
print(output_infer)

Treinamento:
Entrada:
[[ 0.80751739 -1.04174609  0.41735442]
 [-0.21362786 -0.41399812 -1.62113164]
 [ 1.01183818  0.21971938 -1.62029227]]
Saída com Dropout:
[[ 0.         -0.          0.83470884]
 [-0.42725571 -0.82799624 -0.        ]
 [ 2.02367636  0.         -0.        ]]
Máscara aplicada:
[[0 0 1]
 [1 1 0]
 [1 0 0]]

Inferência:
Entrada:
[[ 0.80751739 -1.04174609  0.41735442]
 [-0.21362786 -0.41399812 -1.62113164]
 [ 1.01183818  0.21971938 -1.62029227]]
Saída com Dropout (sem alteração):
[[ 0.80751739 -1.04174609  0.41735442]
 [-0.21362786 -0.41399812 -1.62113164]
 [ 1.01183818  0.21971938 -1.62029227]]


A função tem a saíde esperada. Conseguimos vez que após a aplicação da máscara, durante o treino a saída passa a ter neurónios desativados (0) e ativados, enquanto que no processo de inferência isso não acontece.
Os tamanhos das entradas e saídas são iguais.